[build]
  publish = "."
  command = "echo 'No build command needed'"

[functions]
  directory = "netlify/functions"

# --- ADD THIS ENTIRE BLOCK ---
# This tells Netlify how to handle requests to your proxy function.
[[headers]]
  # Apply these rules to all requests for your proxy function
  for = "/.netlify/functions/proxy"

  [headers.values]
    # Allow requests from your GitHub Pages site
    Access-Control-Allow-Origin = "https://jander15.github.io"
    # Specify which methods are allowed
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    # Specify which headers are allowed
    Access-Control-Allow-Headers = "Content-Type, Authorization"